Repository modorie/moida, pull requests merged in 2022-10, with the labels that each got.

#154 [Feat] Map 컴포넌트 및 테스트 코드 구현
  components/Map/Map.stories.tsx
  components/Map/Map.styled.ts
  components/Map/Map.test.ts
  components/Map/Map.tsx
  components/Map/Map.types.ts
  components/Map/index.ts
  next.config.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: ✨ FEAT, 🧪 TEST

#161 [Feat] 버튼 컴포넌트 리팩토링 및 스타일 수정
  components/Buttons/Button/Button.stories.tsx
  components/Buttons/Button/Button.styled.ts
  components/Buttons/Button/Button.test.tsx
  components/Buttons/Button/Button.tsx
  components/Buttons/FixedButton/FixedButton.stories.tsx
  components/Buttons/FixedButton/FixedButton.styled.ts
  components/Buttons/FixedButton/FixedButton.tsx
  components/Buttons/FloatingButton/FloatingButton.styled.ts
  components/Buttons/FloatingButton/FloatingButton.tsx
  components/Buttons/LoadingDots/LoadingDots.styled.ts
  components/Buttons/LoadingDots/LoadingDots.tsx
  components/Icon/Icon.styled.ts
  components/Icon/Icon.types.ts
  components/Typography/Typography.stories.tsx
  components/Typography/Typography.styled.ts
  components/Typography/Typography.tsx
  components/Typography/Typography.types.ts
  components/Typography/index.ts
  components/index.ts
  foundations/Color/Palette/Palette.stories.tsx
  foundations/Color/Palette/Palette.ts
  foundations/Color/Palette/Palette.types.ts
  foundations/Color/Palette/index.ts
  foundations/Color/Theme/Theme.stories.tsx
  foundations/Color/Theme/Theme.ts
  foundations/Color/Theme/Theme.types.ts
  foundations/Color/Theme/index.ts
  foundations/Transition/Transition.ts
  foundations/index.ts
Labels: ✨ FEAT, 🛠 REFAC

#163 [Feat] Input 컴포넌트 사용성 개선, clear 기능 추가
  components/Input/Input.stories.tsx
  components/Input/Input.tsx
  components/Input/Input.types.ts
  components/Input/controls/Clear/Clear.tsx
  components/Input/controls/Manage/Manage.tsx
  components/Input/controls/Search/Search.tsx
  types/ComponentProps.ts
  utils/makeCombineRefs.ts
Labels: ✨ FEAT
