Repository modorie/moida, pull requests merged in 2022-03, with the labels that each got.

#54 [Feat] Badge 컴포넌트 생성
  components/Badge/Badge.stories.tsx
  components/Badge/Badge.styled.ts
  components/Badge/Badge.tsx
  components/Badge/Badge.types.ts
  foundations/Color/Theme/Theme.stories.tsx
  foundations/Color/Theme/Theme.ts
  foundations/Color/Theme/Theme.types.ts
Labels: ✨ FEAT

#56 [Feat] Transition Foundation 추가
  components/Icon/assets/ChevronLeft.tsx
  components/Icon/assets/ChevronRight.tsx
  components/Icon/assets/Edit.tsx
  components/Icon/assets/List.tsx
  components/Icon/assets/MapPin.tsx
  components/Icon/assets/Menu.tsx
  components/Icon/assets/Search.tsx
  components/Icon/assets/Share.tsx
  components/Icon/assets/Share2.tsx
  components/Icon/assets/Stack.tsx
  components/Icon/assets/X.tsx
  components/Input/Input.styled.ts
  components/Input/controls/Clear/Clear.tsx
  components/StationInfo/LineColor/LineColor.stories.tsx
  components/StationInfo/LineSymbol/LineSymbol.stories.tsx
  components/StationInfo/StationInfo.stories.tsx
  components/StationInfo/StationInfo.tsx
  foundations/Color/Palette/Palette.stories.tsx
  foundations/Color/Theme/Theme.stories.tsx
  foundations/FontSize/FontSize.stories.tsx
  foundations/FontWeight/FontWeight.stories.tsx
  foundations/Transition/Transition.stories.tsx
  foundations/Transition/Transition.ts
  foundations/Transition/index.ts
  foundations/index.ts
Labels: ✨ FEAT

#57 [Feat] GPS 버튼 및 지도 Mark 컴포넌트 생성
  components/GpsButton/GpsButton.stories.tsx
  components/GpsButton/GpsButton.styled.ts
  components/GpsButton/GpsButton.tsx
  components/Icon/Icon.tsx
  components/Icon/Icon.types.ts
  components/Icon/assets/ChevronLeft.tsx
  components/Icon/assets/ChevronRight.tsx
  components/Icon/assets/Edit.tsx
  components/Icon/assets/Gps.tsx
  components/Icon/assets/List.tsx
  components/Icon/assets/MapPin.tsx
  components/Icon/assets/Menu.tsx
  components/Icon/assets/MoreHorizontal.tsx
  components/Icon/assets/MoreVertical.tsx
  components/Icon/assets/Search.tsx
  components/Icon/assets/Share.tsx
  components/Icon/assets/Share2.tsx
  components/Icon/assets/Stack.tsx
  components/Icon/assets/X.tsx
  components/Icon/assets/index.ts
  components/MapMark/MapMark.stories.tsx
  components/MapMark/MapMark.styled.ts
  components/MapMark/MapMark.tsx
  components/StationInfo/StationInfo.tsx
Labels: ✨ FEAT

#59 [Feat] Logo 컴포넌트 생성
  components/Badge/Badge.stories.tsx
  components/Icon/Icon.stories.tsx
  components/Icon/Icon.tsx
  components/Icon/Icon.types.ts
  components/Input/Input.stories.tsx
  components/Logo/Logo.stories.tsx
  components/Logo/Logo.tsx
  components/Logo/Logo.types.ts
  components/Logo/Spacing/Spacing.tsx
  components/Logo/Spacing/index.ts
  components/Logo/Symbol/Symbol.tsx
  components/Logo/Symbol/index.ts
  components/Logo/Wordmark/Wordmark.tsx
  components/Logo/Wordmark/index.ts
  components/Logo/index.ts
  components/StationInfo/LineSymbol/LineSymbol.stories.tsx
  components/Typography/Typography.stories.tsx
Labels: ✨ FEAT

#60 [Feat] HelperText 컴포넌트 생성
  components/Badge/Badge.styled.ts
  components/HelperText/HelperText.stories.tsx
  components/HelperText/HelperText.styled.ts
  components/HelperText/HelperText.tsx
  components/HelperText/HelperText.types.ts
  components/StationInfo/LineSymbol/LineSymbol.styled.ts
  foundations/Color/Palette/Palette.ts
  foundations/Color/Palette/Palette.types.ts
  foundations/Color/Theme/Theme.stories.tsx
  foundations/Color/Theme/Theme.ts
  foundations/Color/Theme/Theme.types.ts
  foundations/Color/Theme/index.ts
Labels: ✨ FEAT

#62 [Feat] 스토리북 기본 Viewport 설정
  .github/workflows/chromatic.yml
  .storybook/preview.tsx
  .storybook/theme.ts
  components/Badge/Badge.stories.tsx
  components/GpsButton/GpsButton.stories.tsx
  components/HelperText/HelperText.stories.tsx
  components/Icon/Icon.stories.tsx
  components/Input/controls/Clear/Clear.stories.tsx
  components/Input/controls/Manage/Manage.stories.tsx
  components/Input/controls/Search/Search.stories.tsx
  components/Logo/Logo.stories.tsx
  components/Logo/Logo.tsx
  components/MapMark/MapMark.stories.tsx
  components/StationInfo/LineColor/LineColor.stories.tsx
  components/StationInfo/LineSymbol/LineSymbol.stories.tsx
  components/StationInfo/StationInfo.stories.tsx
  components/Typography/Typography.stories.tsx
  foundations/Color/Palette/Palette.stories.tsx
  foundations/Color/Theme/Theme.stories.tsx
  foundations/FontSize/FontSize.stories.tsx
  foundations/FontWeight/FontWeight.stories.tsx
  foundations/Transition/Transition.stories.tsx
Labels: ✨ FEAT

#65 [Feat] Button Group 컴포넌트 생성
  components/Badge/index.ts
  components/ButtonGroup/ButtonGroup.stories.tsx
  components/ButtonGroup/ButtonGroup.styled.ts
  components/ButtonGroup/ButtonGroup.tsx
  components/ButtonGroup/ButtonGroup.types.ts
  components/ButtonGroup/Radio/Radio.styled.ts
  components/ButtonGroup/Radio/Radio.tsx
  components/ButtonGroup/Radio/Radio.types.ts
  components/ButtonGroup/Radio/index.ts
  components/ButtonGroup/index.ts
  components/GpsButton/index.ts
  components/HelperText/index.ts
  components/Input/Input.tsx
  components/Input/Input.types.ts
  components/Logo/index.ts
  components/MapMark/index.ts
  components/index.ts
Labels: ✨ FEAT

#76 [Feat] Tab, Tabs 컴포넌트 생성
  components/Input/Input.styled.ts
  components/Tabs/Tab/Tab.stories.tsx
  components/Tabs/Tab/Tab.styled.ts
  components/Tabs/Tab/Tab.tsx
  components/Tabs/Tab/Tab.types.ts
  components/Tabs/Tab/index.ts
  components/Tabs/Tabs.stories.tsx
  components/Tabs/Tabs.styled.ts
  components/Tabs/Tabs.tsx
  components/Tabs/Tabs.types.ts
Labels: ✨ FEAT

#78 [Feat] Header 컴포넌트 생성
  components/Header/Header.stories.tsx
  components/Header/Header.styled.ts
  components/Header/Header.tsx
  components/Header/index.ts
  components/Tabs/index.ts
  components/index.ts
  foundations/Color/Theme/Theme.ts
  foundations/Color/Theme/Theme.types.ts
Labels: ✨ FEAT

#79 feat: 스토리북 패널 위치 오른쪽으로 설정
  .storybook/manager.ts
Labels: ✨ FEAT

#81 [Feat] Navbar 컴포넌트 생성
  components/Badge/Badge.stories.tsx
  components/ButtonGroup/ButtonGroup.stories.tsx
  components/GpsButton/GpsButton.stories.tsx
  components/Header/Header.stories.tsx
  components/HelperText/HelperText.stories.tsx
  components/Icon/Icon.stories.tsx
  components/Input/Input.stories.tsx
  components/Input/controls/Clear/Clear.stories.tsx
  components/Input/controls/Manage/Manage.stories.tsx
  components/Input/controls/Search/Search.stories.tsx
  components/Logo/Logo.stories.tsx
  components/MapMark/MapMark.stories.tsx
  components/Navbar/NavBody/NavBody.styled.ts
  components/Navbar/NavBody/NavBody.tsx
  components/Navbar/NavBody/index.ts
  components/Navbar/NavFooter/NavFooter.styled.ts
  components/Navbar/NavFooter/NavFooter.tsx
  components/Navbar/NavFooter/index.ts
  components/Navbar/NavHeader/NavHeader.styled.ts
  components/Navbar/NavHeader/NavHeader.tsx
  components/Navbar/NavHeader/index.ts
  components/Navbar/NavItem/NavItem.stories.tsx
  components/Navbar/NavItem/NavItem.styled.ts
  components/Navbar/NavItem/NavItem.tsx
  components/Navbar/NavItem/NavItem.types.ts
  components/Navbar/NavItem/index.ts
  components/Navbar/Navbar.stories.tsx
  components/Navbar/Navbar.styled.ts
  components/Navbar/Navbar.tsx
  components/Navbar/Navbar.types.ts
  components/Navbar/index.ts
  components/StationInfo/LineSymbol/LineSymbol.stories.tsx
  components/StationInfo/StationInfo.stories.tsx
  components/Tabs/Tab/Tab.stories.tsx
  components/Tabs/Tabs.stories.tsx
  components/Typography/Typography.stories.tsx
  components/index.ts
  foundations/Color/Palette/Palette.stories.tsx
  foundations/Color/Theme/Theme.stories.tsx
  foundations/FontSize/FontSize.stories.tsx
  foundations/FontWeight/FontWeight.stories.tsx
  foundations/Transition/Transition.stories.tsx
  types/UserProps.ts
Labels: ✨ FEAT, 🛠 REFAC

#83 [Feat] Keyframe foundation 생성
  foundations/Keyframe/Keyframe.stories.tsx
  foundations/Keyframe/Keyframe.ts
  foundations/Keyframe/Keyframe.types.ts
  foundations/Keyframe/index.ts
  foundations/index.ts
Labels: ✨ FEAT

#85 [Feat] Navbar 및 Header 클릭 이벤트 설정
  components/Header/Header.stories.tsx
  components/Header/Header.styled.ts
  components/Header/Header.tsx
  components/Header/Header.types.ts
  components/Navbar/Navbar.styled.ts
  components/Navbar/Navbar.tsx
  components/Navbar/Navbar.types.ts
Labels: ✨ FEAT

#88 [Feat] Navbar 인터렉션 추가
  components/Navbar/NavFooter/NavFooter.tsx
  components/Navbar/NavHeader/NavHeader.styled.ts
  components/Navbar/NavItem/NavItem.styled.ts
Labels: ✨ FEAT

#92 [Feat] Modal 컴포넌트 생성
  components/Modal/Modal.stories.tsx
  components/Modal/Modal.styled.ts
  components/Modal/Modal.tsx
  components/Modal/Modal.types.ts
  components/Modal/index.ts
  components/index.ts
Labels: ✨ FEAT

#96 [Feat] Avatar 컴포넌트 방장 prop 추가
  components/Avatar/Avatar.stories.tsx
  components/Avatar/Avatar.styled.ts
  components/Avatar/Avatar.tsx
  components/Avatar/Avatar.types.ts
  components/Avatar/HostBadge/HostBadge.styled.ts
  components/Avatar/HostBadge/HostBadge.tsx
  components/Avatar/HostBadge/index.ts
  components/Avatar/index.ts
  components/index.ts
Labels: ✨ FEAT

#93 [Feat] Button 컴포넌트 생성
  .storybook/main.ts
  components/Buttons/Button/Button.stories.tsx
  components/Buttons/Button/Button.styled.ts
  components/Buttons/Button/Button.test.tsx
  components/Buttons/Button/Button.tsx
  components/Buttons/Button/Button.types.ts
  components/Buttons/Button/__snapshots__/Button.test.tsx.snap
  components/Buttons/Button/index.ts
  components/Buttons/FixedButton/FixedButton.stories.tsx
  components/Buttons/FixedButton/FixedButton.styled.ts
  components/Buttons/FixedButton/FixedButton.test.tsx
  components/Buttons/FixedButton/FixedButton.tsx
  components/Buttons/FixedButton/FixedButton.types.ts
  components/Buttons/FixedButton/__snapshots__/FixedButton.test.tsx.snap
  components/Buttons/FixedButton/index.ts
  components/Buttons/FloatingButton/FloatingButton.stories.tsx
  components/Buttons/FloatingButton/FloatingButton.styled.ts
  components/Buttons/FloatingButton/FloatingButton.test.tsx
  components/Buttons/FloatingButton/FloatingButton.tsx
  components/Buttons/FloatingButton/FloatingButton.types.ts
  components/Buttons/FloatingButton/__snapshots__/FloatingButton.test.tsx.snap
  components/Buttons/FloatingButton/index.ts
  components/Buttons/LoadingDots/LoadingDots.styled.ts
  components/Buttons/LoadingDots/LoadingDots.tsx
  components/Buttons/LoadingDots/index.ts
  components/Buttons/index.ts
  components/Icon/assets/Edit.tsx
  foundations/Color/Theme/Theme.stories.tsx
  foundations/Color/Theme/Theme.ts
  foundations/Color/Theme/Theme.types.ts
  package.json
  pages/_app.tsx
  types/ComponentProps.ts
  yarn.lock
Labels: ✨ FEAT

#113 [Fix] MapMark 컴포넌트 중심 좌표 수정
  components/MapMark/MapMark.styled.ts
  foundations/Color/Theme/Theme.ts
  foundations/Color/Theme/Theme.types.ts
Labels: 🐞 BUG, ✨ FEAT

#114 [Feat] Navbar 상단을 누르면 Navbar가 닫히는 문제 해결 및 외부 클릭 기능 추가
  components/Navbar/Navbar.styled.ts
  components/Navbar/Navbar.tsx
Labels: 🐞 BUG, ✨ FEAT

#109 [Feat] 테스트 코드 개선
  components/Buttons/Button/Button.stories.tsx
  components/Buttons/Button/Button.styled.ts
  components/Buttons/Button/Button.test.tsx
  components/Buttons/Button/__snapshots__/Button.test.tsx.snap
  components/Buttons/FixedButton/FixedButton.test.tsx
  components/Buttons/FixedButton/__snapshots__/FixedButton.test.tsx.snap
  components/Buttons/FloatingButton/FloatingButton.test.tsx
  components/Buttons/FloatingButton/__snapshots__/FloatingButton.test.tsx.snap
  components/Input/Input.test.tsx
  components/Input/__snapshots__/Input.test.tsx.snap
  components/Typography/Typography.test.tsx
  components/Typography/__snapshots__/Typography.test.tsx.snap
  package.json
Labels: ✨ FEAT
